---
- name: Desplegar Backend Node.js con PM2
  hosts: webserver
  become: yes
  vars:
    app_port: "3000"

  tasks:
    - name: Instalar Git, Curl, Node.js y npm
      apt:
        name:
          - git
          - curl
          - nodejs
          - npm
        state: present
        update_cache: yes

    - name: Instalar PM2 globalmente
      npm:
        name: pm2
        global: yes

    - name: Crear directorio de la aplicación
      file:
        path: /var/www/backend
        state: directory
        owner: deployer
        group: deployer
        mode: "0755"

    - name: Clonar o actualizar el repositorio
      git:
        repo: "https://github.com/YampierPonceV/bklogin.git"
        dest: /var/www/backend
        version: main
        force: yes
      become: no

    - name: Crear archivo .env usando secretos de Ansible Vault
      copy:
        dest: /var/www/backend/.env
        content: |
          PORT={{ app_port }}
          DB_HOST={{ vault_db_host }}
          DB_PORT={{ vault_db_port }}
          DB_NAME={{ vault_db_name }}
          DB_USER={{ vault_db_user }}
          DB_PASSWORD={{ vault_db_password }}
        owner: deployer
        group: deployer
        mode: "0600"

    - name: Instalar dependencias del proyecto (npm install)
      npm:
        path: /var/www/backend
      become: no

    - name: Iniciar o recargar la aplicación con PM2
      command: pm2 startOrReload ecosystem.config.js --env production
      args:
        chdir: /var/www/backend
      become: no

    - name: Guardar la lista de procesos de PM2
      command: pm2 save
      become: no
